playwright:
  stage: testing
  # Using this docker image
  image: ghcr.io/arne1303/php-playwright-docker:main
  # database services when required
  services:
    - name: ${MARIA_DB_IMAGE}
      alias: mariadb
      command: ["--default_authentication_plugin=mysql_native_password"]
  # Setup dependencies and Seed database, you might want to split this into separate jobs depending on you're own pipeline
  before_script:
    - cp .env.example .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - npm install --pure-lockfile
    - npm run dev
    - php artisan migrate:fresh --force
    - php artisan db:seed
    - npx playwright -V
  # Running playwright test and exporting junit report
  script:
    - PLAYWRIGHT_JUNIT_OUTPUT_NAME=playwright-report.xml npx playwright test --reporter=junit
  artifacts:
    expire_in: 1 week
    paths:
      - php-server.log # Php server output for debug
      - test-results/ # Possible traces
    reports:
      junit: playwright-report.xml
    when: always